export const ProductsList = [
    {
      id: 1,
      ano: 2023,
      category: "resumo_expandido",
      description1: "VICENZI, L. N.; JANUÁRIO, J. A.; JULIÃO, T. S.; ROTHEBARTH, A. V. P. ",
      clicked: "Panorama sobre a constituição sociocultural da comunidade enxadrística feminina brasileira a partir de uma perspectiva de gênero do subcampo esportivo do xadrez.",
      description2: "In: VIII Congresso Latino-Americano de Estudos Socioculturais do Esporte, 2023, Maringá. ",
      description3: "Caderno de resumos e informações",
      description4: ", 2023.",
      link: "https://drive.google.com/file/d/1GEpAUGcsEU4D9NkLTxGEMVjdh77hhCL6/view",
    },
    {
        id: 2,
        ano: 2021,
        category: "noticias",
        description1: "JANUÁRIO, J. Conheça mulheres que fizeram história no xadrez. Disponível em: <",
        clicked: "https://mail.bvl.org.br/noticia/conhea-mulheres-que-fizeram-histria-no-xadrez",
        description2: ">. Acesso em: 13 jul. 2023.",
        link: "https://mail.bvl.org.br/noticia/conhea-mulheres-que-fizeram-histria-no-xadrez",
    },
    {
      id: 3,
      ano: 2020,
      category: "capitulo_livro",
      description1: "SANTANA, C. M.; JANUÁRIO, J. A.; AURIEMO, D. F. ",
      clicked: "A formação de agentes responsáveis pelo processo de ensino-aprendizagem no xadrez: uma análise quantitativa do contexto brasileiro. ",
      description2: "In: Solange Aparecida de Souza Monteiro (Org.). ",
      description3: "A Educação no Brasil e no Mundo:",
      description4: "Avanços, Limites e Contradições 3. 1ed .Ponta Grossa: Atena Editora, 2020, v. 3, p. 1-351.",
      link: "https://www.atenaeditora.com.br/catalogo/post/a-formacao-de-agentes-responsaveis-pelo-processo-de-ensino-aprendizagem-do-xadrez-uma-analise-quantitativa-do-contexto-brasileiro",
    },
    {
      id: 4,
      ano: 2017,
      category: "mestrado",
      description1: "JANUÁRIO, J. ",
      description2: "A herança na trajetória esportiva de Grandes Mestres brasileiros: ",
      description3: "processos educacionais e esportivos de formação de uma elite cultural. ",
      description4: "2017. 572 f. Dissertação (Programa de Pós-Graduação em Educação) – Faculdade de Filosofia, Ciências e Letras de Ribeirão Preto, Universidade de São Paulo, Ribeirão Preto, 2017.",
      link: "https://www.teses.usp.br/teses/disponiveis/59/59140/tde-03022021-180536/",
    },
    {
      id: 5,
      ano: 2016,
      category: "noticias",
      description1: "JANUÁRIO, J. Pesquisa mostra que família influencia no desempenho de crianças que jogam xadrez. Disponível em: <",
      clicked: "https://memoria.ebc.com.br/infantil/para-pais/2016/03/pesquisa-mostra-que-familia-influencia-no-desempenho-de-criancas-que",
      description2: ">. Acesso em: 13 jul. 2023.",
      link: "https://memoria.ebc.com.br/infantil/para-pais/2016/03/pesquisa-mostra-que-familia-influencia-no-desempenho-de-criancas-que",
    },
    {
      id: 6,
      ano: 2015,
      category: "resumo_expandido",
      description1: "JANUÁRIO, J. A.; MARQUES, R. F. R. ",
      clicked: "Ser Grande Mestre no Brasil - A Influência do Contexto Brasileiro no Profissionalismo da Carreira de Alto Rendimento no Xadrez. ",
      description2: "In: VI Congresso Internacional de Pedagogia do Esporte, 2015, Maringá. ",
      description3: "Anais do VI Congresso Internacional de Pedagogia do Esporte",
      description4: ", 2015.",
      link: "https://www.researchgate.net/publication/308415901_Ser_grande_mestre_no_Brasil_A_influencia_do_contexto_brasileiro_no_profissionalismo_da_carreira_de_alto_rendimento_no_xadrez",
    },
    {
      id: 7,
      ano: 2015,
      category: "resumo_expandido",
      description1: "JANUÁRIO, J. A.; MARQUES, R. F. R. ",
      clicked: "O Ambiente Escolar como Via de Transmissão Heterodoxa do Habitus Enxadrístico no Subcampo Esportivo do Xadrez Brasileiro. ",
      description2: "In: I Jornada Pierre Bourdieu e o Ensino de Ciências, 2015, São Paulo. ",
      description3: "Anais da I Jornada Pierre Bourdieu e o Ensino de Ciências",
      description4: ", 2015.",
      link: "http://fep.if.usp.br/~profis/Jornadas/2015/ATAS_I_Jornada_Pierre_Bourdieu_2015.pdf",
    },
    {
      id: 8,
      ano: 2015,
      category: "resumo_expandido",
      description1: "JANUÁRIO, J. A.; MARQUES, R. F. R. ",
      clicked: "O ensino do xadrez no Brasil: aspectos socioculturais e pedagógicos no subcampo esportivo enxadrístico. ",
      description2: "In: 1º Seminário de Pesquisa do Programa de Pós-Graduação em Educação & X Mostra de Trabalhos de Pesquisa do Curso de Pedagogia, 2015, Ribeirão Preto (SP). ",
      description3: "Caderno de Programação e de Resumos: 1º Seminário de Pesquisa do Programa de Pós-Graduação em Educação & X Mostra de Trabalhos de Pesquisa do Curso de Pedagogia",
      description4: ", 2015. p. 28-29.",
    },
    {
      id: 9,
      ano: 2015,
      category: "noticias",
      description1: "JANUÁRIO, J. Influência familiar incentiva prática do xadrez. Disponível em: <",
      clicked: "https://www5.usp.br/noticias/ comportamento/influencia-familiar-incentiva-pratica-do-xadrez/",
      description2: ">. Acesso em: 13 jul. 2023.",
      link: "https://www5.usp.br/noticias/comportamento/influencia-familiar-incentiva-pratica-do-xadrez/",
    },
    {
      id: 10,
      ano: 2015,
      category: "noticias",
      description1: "JANUÁRIO, J. I Congreso Internacional de Ajedrez de Brasil. Disponível em: <",
      clicked: "https://es.chessbase.com/post/i-congreso-internacional-de-ajedrez-de-brasil",
      description2: ">. Acesso em: 13 jul. 2023.",
      link: "https://es.chessbase.com/post/i-congreso-internacional-de-ajedrez-de-brasil",
    },
    {
      id: 11,
      ano: 2014,
      category: "monografia",
      description1: "JANUÁRIO, J. ",
      description2: "Trajetória esportiva de grandes mestres brasileiros: ",
      description3: "aspectos socioculturais e pedagógicos no campo social do xadrez. ",
      description4: "2014. 67 f. Trabalho de conclusão de curso (Bacharelado em Educação Física e Esporte) – Escola de Educação Física e Esporte de Ribeirão Preto, Universidade de São Paulo, Ribeirão Preto, 2014.",
    },
    {
      id: 12,
      ano: 2018,
      category: "seminario",
      description1: "RUTHEBARTH, A. V. P.; WATANUKI, H. M. ",
      clicked: "A LUDICIDADE NO AMBIENTE CORPORATIVO VISANDO QUALIDADE DE VIDA NO TRABALHO: a prática do jogo de xadrez entre funcionários de uma empresa. ",
      description2: "In: XXI Seminários em Administração, 2018, São Paulo (SP). ",
      description3: "Caderno de Programação e de Resumos: XXI SEMEAD - Seminários em Administração.",
      description4: ", 2018.",
    },
    {
      id: 13,
      ano: 2023,
      category: "extras",
      description1: "LBXF - Liga Brasileira de Xadrez Feminino. Panorama Xadrez Feminino Brasileiro 2023. Disponível em: <",
      clicked: "/materiais/Infográfico - figura.png",
      description2: ">. Publicado no Instagram.",
      link: "/materiais/Infográfico - figura.png",
    },
    {
      id: 14,
      ano: 2023,
      category: "extras",
      description1: "LBXF - Liga Brasileira de Xadrez Feminino. O que é a Liga Brasileira de Xadrez Feminino?. Disponível em: <",
      clicked: "/materiais/Informe LBXF - figura.png",
      description2: ">. Publicado no Instagram.",
      link: "/materiais/Informe LBXF - figura.png",
    },
    {
      id: 15,
      ano: 2023,
      category: "extras",
      description1: "LBXF - Liga Brasileira de Xadrez Feminino. Curso Formação Básica em Xadrez Feminino. Disponível em: <",
      clicked: "/materiais/Curso Formação Básica em Xadrez Feminino.pdf",
      description2: ">. Publicado no Instagram.",
      link: "/materiais/Curso Formação Básica em Xadrez Feminino.pdf",
    },
    {
      id: 16,
      ano: 2024,
      category: "artigos",
      description1: "JANUÁRIO, J. A.; GIGLIO, S. S.; AMARAL, S. C. F. ",
      clicked: "Grandmasters, distinct elite: taste submitted to discussion from the social conditioning factors of the predilection for chess. ",
      description3: "International Review for the Sociology of Sport",
      description4: ", v. 59, p. 1-16, 2024.",
      link: "https://journals.sagepub.com/doi/10.1177/10126902231226088",
    },
    {
      id: 17,
      ano: 2024,
      category: "artigos",
      description1: "JANUÁRIO, J. A. ",
      clicked: "A herança na trajetória esportiva de um dos Grandes Mestres brasileiros: processos educacionais e esportivos de formação de uma elite cultural. ",
      description3: "Movimento",
      description4: ", v. 29, p. 1-15, 2023.",
      link: "https://seer.ufrgs.br/index.php/Movimento/article/view/129244",
    },
  ];