"use client";
import { useEffect, useState } from 'react';
import TopMenu from "@/components/TopMenu";
import "./globals.css";
import { Rajdhani } from "next/font/google";
import BreadCumbs from "@/components/BreadCumps";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";
import Head from "@/components/Head";
import { I18nextProvider } from 'react-i18next';


import global_pt from "./locales/pt/global.json";
import global_en from "./locales/en/global.json";
import global_es from "./locales/es/global.json";
import global_fr from "./locales/fr/global.json";
import i18next from "i18next";

i18next.init({
  interpolation: {escapeValue: false},
  lng: "pt",
  resources:{
    pt:{
      global: global_pt
    },
    en:{
      global: global_en
    },
    es:{
      global: global_es
    },
    fr:{
      global: global_fr
    },

  }
})


const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isHomePage = pathname === "/home";
  const [currentPath, setCurrentPath] = useState(pathname);
  
  useEffect(() => {
    // Atualiza o estado local quando o caminho muda
    setCurrentPath(pathname);
  }, [pathname]);

  useEffect(() => {
    const handleRouteChange = () => {
      // Usa o estado local atualizado quando o evento ocorre
      window.gtag('config', process.env.NEXT_PUBLIC_GA_ID as string, {
        page_path: currentPath,
      });
    };

    // Adiciona um ouvinte de evento global ao documento.
    document.addEventListener('beforeNavigate', handleRouteChange);

    return () => {
      // Remove o ouvinte de evento ao desmontar o componente.
      document.removeEventListener('beforeNavigate', handleRouteChange);
    };
  }, [currentPath]);

  return (
    <I18nextProvider i18n={i18next}>
        <html lang="pt-br" className={`${rajdhani.className} ${isHomePage ? "bg-mediumpink" : "bg-white"}`}>
      
      <Head 
            title = "LBXF | Liga Brasileira de Xadrez Feminino"
            description = "Generated by create next app"
        />
      <body>
        <Toaster />
        <TopMenu />
        
        <div className="mx-12 min-h-screen">
          {/* <div className="mt-6">
            <BreadCumbs />
          </div> */}
          {children}
        </div>
        <Footer />
      </body>
      
    </html>
    </I18nextProvider>
    
  );
}
